import React, { useMemo, useState } from 'react';
import { Header, ArtifactTab } from '@/shared/Header';
import { AssistantPanel } from '@/shared/AssistantPanel';
import { PublicCompsLandingPage } from './components/LandingPage';
import { PublicCompsDashboard } from './components/Dashboard';
import { PublicCompsArtifactView, PublicCompsArtifact } from './components/ArtifactView';
import { Peer } from './data/mockData';
import { getLatestReferenceDate } from './lib/stats';
import {
  fetchFinancialsForDiscovered,
  generateInsights,
  discoverPeers,
  assistantChatStream,
  AssistantStatePatch,
  DiscoveredPeer,
  ParsedFilters,
  CustomConstraint,
  DiscoveryFilters,
} from './lib/api';

const PUBLIC_COMPS_REASONING = (
  <>
    <p className="mb-2">
      You're in <span className="font-medium text-gray-900">Trading comps</span> mode. Peer set is discovered via
      Perplexity, financials populated from Yahoo Finance, and the commentary below the table is generated by GPT.
    </p>
    <p>
      Suggested peers ranked on: <span className="italic">business model overlap</span>,{' '}
      <span className="italic">revenue scale</span>, and <span className="italic">geography</span>.
    </p>
  </>
);

const PUBLIC_COMPS_PROMPTS = [
  'Drop peers with market cap > $20B',
  'Show me only peers with NTM consensus',
  'Flag peers with EBITDA margin below 10%',
];

const EMPTY_FILTERS: ParsedFilters = {
  company: null,
  sector: null,
  geography: null,
  marketCap: null,
  revenue: null,
  qualitative: null,
};

function StatusBanner({ failedTickers }: { failedTickers: string[] }) {
  if (failedTickers.length === 0) return null;
  return (
    <div className="px-4 py-2 text-xs border-b border-amber-200 bg-amber-50 text-amber-900">
      <span className="font-semibold">Skipped {failedTickers.length} ticker{failedTickers.length === 1 ? '' : 's'}.</span>{' '}
      Yahoo Finance had no data for: <span className="font-mono">{failedTickers.join(', ')}</span>
    </div>
  );
}

interface PublicCompsAppProps {
  assistantCollapsed: boolean;
  onToggleAssistant: () => void;
}

export function PublicCompsApp({ assistantCollapsed, onToggleAssistant }: PublicCompsAppProps) {
  const [mode, setMode] = useState<'landing' | 'dashboard'>('landing');
  const [targetCompany, setTargetCompany] = useState('NovaPulse Medical');
  const [peers, setPeers] = useState<Peer[]>([]);
  const [insights, setInsights] = useState<string | null>(null);
  const [insightsLoading, setInsightsLoading] = useState(false);
  const [insightsError, setInsightsError] = useState<string | null>(null);
  const [artifacts, setArtifacts] = useState<PublicCompsArtifact[]>([]);
  const [activeView, setActiveView] = useState<'dashboard' | 'artifact'>('dashboard');
  const [activeArtifactId, setActiveArtifactId] = useState<string | null>(null);
  const [failedTickers, setFailedTickers] = useState<string[]>([]);
  const [isFetching, setIsFetching] = useState(false);

  // Filter state used for the current dashboard — editable from the FilterBar at top.
  const [appliedFilters, setAppliedFilters] = useState<ParsedFilters>(EMPTY_FILTERS);
  const [appliedCustomFilters, setAppliedCustomFilters] = useState<CustomConstraint[]>([]);
  const [appliedDescription, setAppliedDescription] = useState<string>('');
  const [isRediscovering, setIsRediscovering] = useState(false);
  const [rediscoverError, setRediscoverError] = useState<string | null>(null);

  const referenceDate = useMemo(() => getLatestReferenceDate(peers), [peers]);

  const refreshInsights = async (target: string, currentPeers: Peer[]) => {
    setInsightsLoading(true);
    setInsightsError(null);
    try {
      const text = await generateInsights(target, currentPeers);
      setInsights(text);
    } catch (err) {
      setInsightsError(err instanceof Error ? err.message : 'Insights failed');
      setInsights(null);
    } finally {
      setInsightsLoading(false);
    }
  };

  const handleRunAnalysis = async ({
    targetCompany: target,
    discovered,
    selectedTickers,
    filters,
    customFilters,
    description,
  }: {
    targetCompany: string;
    discovered: DiscoveredPeer[];
    selectedTickers: Set<string>;
    filters: ParsedFilters;
    customFilters: CustomConstraint[];
    description: string;
  }) => {
    setTargetCompany(target);
    setAppliedFilters(filters);
    setAppliedCustomFilters(customFilters);
    setAppliedDescription(description);
    setIsFetching(true);
    setInsights(null);
    setInsightsError(null);

    const selected = discovered.filter((d) => selectedTickers.has(d.ticker));
    const result = await fetchFinancialsForDiscovered(selected);

    setPeers(result.peers);
    setFailedTickers(result.failedTickers);
    setIsFetching(false);
    setMode('dashboard');
    setActiveView('dashboard');

    if (result.peers.length > 0) {
      await refreshInsights(target, result.peers);
    }
  };

  const handleRediscover = async (
    nextFilters: ParsedFilters,
    nextCustomFilters: CustomConstraint[],
    nextDescription: string
  ) => {
    setIsRediscovering(true);
    setRediscoverError(null);
    setInsights(null);
    setInsightsError(null);

    try {
      const dFilters: DiscoveryFilters = {
        sector: nextFilters.sector ?? undefined,
        geography: nextFilters.geography ?? undefined,
        marketCap: nextFilters.marketCap ?? undefined,
        revenue: nextFilters.revenue ?? undefined,
        qualitative: nextFilters.qualitative ?? nextDescription ?? undefined,
        customConstraints: nextCustomFilters,
      };
      const company = nextFilters.company ?? nextFilters.sector ?? targetCompany;
      const discovered = await discoverPeers(company, dFilters);
      if (discovered.length === 0) {
        setRediscoverError('No peers discovered. Try loosening the filters.');
        setIsRediscovering(false);
        return;
      }

      const result = await fetchFinancialsForDiscovered(discovered);

      const target = nextFilters.company ?? nextFilters.sector ?? targetCompany;
      setTargetCompany(target);
      setAppliedFilters(nextFilters);
      setAppliedCustomFilters(nextCustomFilters);
      setAppliedDescription(nextDescription);
      setPeers(result.peers);
      setFailedTickers(result.failedTickers);
      setIsRediscovering(false);

      if (result.peers.length > 0) {
        await refreshInsights(target, result.peers);
      }
    } catch (err) {
      setRediscoverError(err instanceof Error ? err.message : 'Re-discovery failed');
      setIsRediscovering(false);
    }
  };

  const handleBackToLanding = () => {
    setMode('landing');
    setActiveView('dashboard');
    setActiveArtifactId(null);
    setRediscoverError(null);
  };

  const handleTogglePeer = (ticker: string) => {
    setPeers((prev) =>
      prev.map((p) =>
        p.ticker === ticker
          ? {
              ...p,
              status: p.status === 'Included' ? 'Excluded' : 'Included',
              exclusionReason: p.status === 'Included' ? 'Manually excluded' : null,
            }
          : p
      )
    );
  };

  const handleSaveArtifact = () => {
    const newArtifact: PublicCompsArtifact = {
      id: Date.now().toString(),
      name: `Public Comps Snapshot — ${new Date().toLocaleDateString()}`,
      date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
      targetCompany,
      referenceDate,
      peers: peers.map((p) => ({ ...p })),
    };
    setArtifacts((prev) => [...prev, newArtifact]);
    setActiveArtifactId(newArtifact.id);
    setActiveView('artifact');
  };

  const handleRegenerateInsights = () => {
    if (peers.length === 0) return;
    void refreshInsights(targetCompany, peers);
  };

  const handleBackToDashboard = () => {
    setActiveView('dashboard');
    setActiveArtifactId(null);
  };

  const activeArtifact = artifacts.find((a) => a.id === activeArtifactId);

  const artifactTabs: ArtifactTab[] = artifacts.map((a) => ({
    id: a.id,
    name: a.name,
    subtitle: `${a.date} · ${a.peers.filter((p) => p.status === 'Included').length} peers`,
  }));

  const applyAssistantPatch = (patch: AssistantStatePatch) => {
    if (patch.targetCompany !== undefined) setTargetCompany(patch.targetCompany);
    if (patch.description !== undefined) setAppliedDescription(patch.description);
    if (patch.filters !== undefined) setAppliedFilters(patch.filters as ParsedFilters);
    if (patch.customFilters !== undefined) setAppliedCustomFilters(patch.customFilters);
    if (patch.peers !== undefined) setPeers(patch.peers);
    if (patch.insights !== undefined) setInsights(patch.insights);
    if (patch.failedTickers !== undefined) setFailedTickers(patch.failedTickers);
    if (patch.mode === 'dashboard') {
      setMode('dashboard');
      setActiveView('dashboard');
    } else if (patch.mode === 'landing') {
      setMode('landing');
    }
  };

  const handleAssistantSend = async (
    userMessage: string,
    history: { role: string; content: string; timestamp: string }[],
    ctx: { pushStatus: (text: string) => void }
  ): Promise<string> => {
    const chatMessages = history
      .filter((m) => m.role === 'user' || m.role === 'assistant')
      .map((m) => ({ role: m.role as 'user' | 'assistant', content: m.content }));
    return assistantChatStream(
      chatMessages,
      {
        mode,
        targetCompany,
        description: appliedDescription,
        filters: appliedFilters,
        customFilters: appliedCustomFilters,
        peers,
        insights,
      },
      {
        onStatus: ctx.pushStatus,
        onStatePatch: applyAssistantPatch,
        onError: (msg) => ctx.pushStatus(`⚠️ ${msg}`),
      }
    );
  };

  const assistantProps = {
    title: 'Public Comps Assistant',
    initialMessages: [],
    reasoningContent: PUBLIC_COMPS_REASONING,
    suggestedPrompts: PUBLIC_COMPS_PROMPTS,
    autoReplyText:
      "Got it — I've adjusted the peer set. The summary stats and insights panel refresh automatically.",
    collapsed: assistantCollapsed,
    onToggleCollapsed: onToggleAssistant,
    onSend: handleAssistantSend,
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden">
      <Header
        title={targetCompany}
        breadcrumbs={
          mode === 'landing'
            ? ['Medtech', 'Public Comps']
            : ['Medtech', 'Public Comps', targetCompany]
        }
        artifacts={artifactTabs}
        activeView={activeView}
        showTabs={mode === 'dashboard'}
        onViewDashboard={handleBackToDashboard}
        onViewArtifact={(id) => {
          setActiveArtifactId(id);
          setActiveView('artifact');
        }}
      />

      <main className="flex-1 flex overflow-hidden">
        {mode === 'landing' ? (
          <>
            <div className="flex-1 flex flex-col min-w-0 border-r border-gray-200">
              <PublicCompsLandingPage onRunAnalysis={handleRunAnalysis} isRunning={isFetching} />
            </div>
            <AssistantPanel {...assistantProps} />
          </>
        ) : (
          <>
            <div className="flex-1 flex flex-col min-w-0 border-r border-gray-200">
              <StatusBanner failedTickers={failedTickers} />
              {activeView === 'dashboard' || !activeArtifact ? (
                <PublicCompsDashboard
                  targetCompany={targetCompany}
                  referenceDate={referenceDate}
                  peers={peers}
                  onTogglePeer={handleTogglePeer}
                  onSaveArtifact={handleSaveArtifact}
                  insights={insights}
                  insightsLoading={insightsLoading}
                  insightsError={insightsError}
                  onRegenerateInsights={handleRegenerateInsights}
                  appliedFilters={appliedFilters}
                  appliedCustomFilters={appliedCustomFilters}
                  appliedDescription={appliedDescription}
                  onRediscover={handleRediscover}
                  isRediscovering={isRediscovering}
                  rediscoverError={rediscoverError}
                  onBackToLanding={handleBackToLanding}
                />
              ) : (
                <PublicCompsArtifactView artifact={activeArtifact} onBack={handleBackToDashboard} />
              )}
            </div>
            <AssistantPanel {...assistantProps} />
          </>
        )}
      </main>
    </div>
  );
}
